# Generated by Django 4.2.3 on 2023-09-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('warehouse', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.warehouse')),
            ],
        ),
    ]
