# Generated by Django 4.1.2 on 2023-11-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='raw_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.rawmaterial'),
        ),
    ]
