# Generated by Django 4.1.2 on 2023-11-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_order',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
