# Generated by Django 4.1.2 on 2023-11-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_order_delete_painting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
