# Generated by Django 4.1.2 on 2024-01-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Awaiting Confirmation', 'Awaiting Confirmation'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready', 'Ready'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default='Awaiting Confirmation', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ordered_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
