# Generated by Django 4.1.2 on 2024-03-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_purchase_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='ordered_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
