# Generated by Django 4.1.2 on 2024-03-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_purchase_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturing',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ordered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
