# Generated by Django 4.1.2 on 2024-03-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_manufacturing_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturing',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturing',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
