# Generated by Django 4.1.2 on 2024-03-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_manufacturing_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
